name: GitHub Actions - Main Workflow

on:
  push:
    branches: 
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - run: npm run message